### ISSUE TITLE
Note that you need to blow up heart blocks?

### ISSUE THREAD

**Issue by GanerCodes** [Deadlydiamond98/HealingPrettyGoodWiki#1]
I spent a long time breaking and replacing heart blocks before I realized I needed to blow them up; honestly I'd prefer shards from pickaxe (so fortune works) and silk touch is solely used to get the block

**Comment by GanerCodes** [comment]
also, apparently i can't craft anything from this mod :/

**Comment by Deadlydiamond98** [comment]
For the Heart Crystal Drops, it does drop, it's just that it's only a small percent chance, and it's a diamond pickaxe level drop.

For the recipes, that was an oversight on my behalf, as many things had changed in JSON for 1.21, and I hadn't realized that something had changed in recipes. I have just fixed this, and the new bugfix update is being pushed onto Curse Forge. Thank you for bringing this issue to my attentions! :)

As for the license, it's All Rights Reserved; I have it listed on Curseforge and Modrinth as such.

**Comment by GanerCodes** [comment]
1. I've broken 1000s of blocks by hand and it hasn't dropped
2. glad its fixed :>
3. alright; i def recommend going open source however
